source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hjanuschka/mypods.git'
source 'git@gitlab.krone.at:mobile/KMMPODS.git'
use_frameworks!
platform :ios, "8.0"


target "bigproj" do

	 pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :branch => 'master'
    #pod 'AcknowledgementsBundle'
    pod 'UIColor-HexString', :git=>'https://github.com/hjanuschka/UIColor-HexString.git'
    pod "CustomKINWebBrowser"
# pod 'Google/Analytics'
    pod 'GoogleAnalytics'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'ISRefreshControl', '~> 1.4.1'
    pod 'OneSignal'
    pod 'UIAlertView+Blocks', '~> 0.8'
    pod 'iRate', '~> 1.11'
    #pod 'PSUpdateApp', '~> 2.0'
    pod 'NSString-HYPContainsString', :git =>'https://github.com/hyperoslo/NSString-HYPContainsString.git'
    pod 'UITableView-NXEmptyView'
    pod 'Fabric'
    pod 'Crashlytics'
    #pod 'GBDeviceInfo'
    pod 'IQKeyboardManager'
    pod 'DAAppsViewController'
    pod 'EAIntroView'
    #pod 'AdTech-SDK'
    pod 'FXForms'
    pod 'TWSReleaseNotesView'
    #pod 'UIView+UIImageEffects'
    pod 'NSString-UrlEncode', :git => 'https://github.com/kevinrenskers/NSString-URLEncode.git'
    pod "SpinKit"
    pod "MRoundedButton", :git => "https://github.com/rohanaurora/MRoundedButton.git"
    pod 'REFrostedViewController'
    pod 'DCKeyValueObjectMapping'
    pod 'NSObject-ObjectMap'
    pod 'FXBlurView'
    pod 'LGPlaceholderView'
    pod "RMStepsController",:git=>"https://github.com/CooperRS/RMStepsController.git",  :branch => "UnlimitedSteps"
    pod 'UIActionSheet-Blocks'
    pod 'UIImage-ResizeMagick'
    pod 'DateTools'
    pod 'FXNotifications'
    pod 'SimulatorRemoteNotifications'
    pod 'M13BadgeView'
    pod 'FLAnimatedImage'
    pod 'JVFloatLabeledTextField'
    pod 'PNChart'
    pod 'HCSStarRatingView'
    pod 'ZLSwipeableView'

end

